python train.py --dataset CIFAR10 \
       --data_path ./data \
       --model PreResNet20 \
       --epochs=150 \
       --lr_init=0.1 \
       --wd=3e-4 \
       --name example/resnet \
       --wl-weight 8 \
       --wl-grad 8 \
       --wl-momentum 8 \
       --wl-activate 8 \
       --wl-error 8 \
       --seed 100 \
       --batch_size 128  \
       --weight-rounding stochastic \
       --activate-rounding stochastic \
       --grad-rounding stochastic \
       --error-rounding stochastic \
       --momentum-rounding stochastic \
       --weight-type block \
       --activate-type block \
       --grad-type block \
       --error-type block \
       --momentum-type block \
       --auto_low;
