python train.py --dataset CIFAR10 \
       --data_path ./data \
       --model PreResNet20 \
       --epochs=150 \
       --lr_init=0.1 \
       --wd=3e-4 \
       --name example/resnet \
       --wl-weight 10 \
       --wl-grad 10 \
       --wl-momentum 10 \
       --wl-activate 10 \
       --wl-error 10 \
       --seed 100 \
       --batch_size 128  \
       --weight-rounding nearest \
       --activate-rounding nearest \
       --grad-rounding nearest \
       --error-rounding nearest \
       --momentum-rounding nearest \
       --weight-type block \
       --activate-type block \
       --grad-type block \
       --error-type block \
       --momentum-type block \
       --auto_low;
