python train.py --dataset CIFAR10 \
       --data_path ./data \
       --model VGG16 \
       --epochs=200 \
       --lr_init=0.05 \
       --wd=5e-4 \
       --name example \
       --wl-weight -1 \
       --wl-grad -1 \
       --wl-momentum -1 \
       --wl-activate -1 \
       --wl-error -1 \
       --fl-weight -1 \
       --fl-grad -1 \
       --fl-momentum -1 \
       --fl-activate -1 \
       --fl-error -1 \
       --seed 100 \
       --batch_size 128  \
       --weight-rounding stochastic \
       --grad-rounding stochastic \
       --momentum-rounding stochastic \
       --weight-type full \
       --grad-type full \
       --momentum-type full;
