python train.py --dataset CIFAR10 \
    --data_path ./data \
    --model VGG16 \
    --epochs=200 \
    --lr_init=0.05 \
    --wd=5e-4 \
    --name single \
    --wl-weight -1 \
    --wl-grad -1 \
    --wl-momentum -1 \
    --wl-activate -1 \
    --wl-error -1 \
    --seed 100 \
    --batch_size 128;
