python train.py --dataset CIFAR10 \
       --data_path ./data \
       --model VGG16 \
       --epochs=200 \
       --lr_init=0.05 \
       --wd=5e-4 \
       --name example \
       --wl-weight 12 \
       --wl-grad 12 \
       --wl-momentum 12 \
       --wl-activate 12 \
       --wl-error 12 \
       --seed 100 \
       --batch_size 128  \
       --weight-rounding nearest \
       --activate-rounding nearest \
       --grad-rounding nearest \
       --error-rounding nearest \
       --momentum-rounding nearest \
       --weight-type block \
       --activate-type block \
       --grad-type block \
       --error-type block \
       --momentum-type block \
       --auto_low;
